In [5]:
from jmetal.algorithm.multiobjective.gde3 import GDE3
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.algorithm.multiobjective.smpso import SMPSO
from jmetal.core.quality_indicator import *
from jmetal.lab.experiment import Experiment, Job, generate_summary_from_experiment
from jmetal.operator import PolynomialMutation, SBXCrossover
from jmetal.util.archive import CrowdingDistanceArchive
from jmetal.util.termination_criterion import StoppingByEvaluations
from jmetal.lab.experiment import generate_boxplot, generate_latex_tables, compute_mean_indicator, compute_wilcoxon
from jmetal.lab.statistical_test.bayesian import *
from jmetal.lab.statistical_test.functions import *
from jmetal.lab.visualization import CDplot, plot_posterior
from jmetal.algorithm.multiobjective import NSGAII
from jmetal.operator import SBXCrossover, PolynomialMutation
from jmetal.problem import DTLZ2
from jmetal.util.termination_criterion import StoppingByEvaluations

In [6]:
problem = DTLZ2(number_of_objectives=3)

algorithm = SMPSO(
    problem=problem,
    swarm_size=100,
    mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables,
                                distribution_index=20),
    leaders=CrowdingDistanceArchive(100),
    termination_criterion=StoppingByEvaluations(max_evaluations=25000)
)

algorithm.run()

In [7]:
from jmetal.util.solution import get_non_dominated_solutions, print_function_values_to_file, print_variables_to_file

front = get_non_dominated_solutions(algorithm.get_result())

# save to files
print_function_values_to_file(front, 'FUN.SMPSO.DTLZ2_3')
print_variables_to_file(front, 'VAR.SMPSO.DTLZ2_3')

2023-09-27 12:04:49,131 [MainThread  ] [INFO ]  Output file (function values): FUN.SMPSO.DTLZ2_3
2023-09-27 12:04:49,143 [MainThread  ] [INFO ]  Output file (variables): VAR.SMPSO.DTLZ2_3


In [8]:
from jmetal.lab.visualization import Plot
# plot_front = Plot(title='Pareto front approximation', axis_labels=['x', 'y'])
plot_front = Plot(title='Pareto front approximation', axis_labels=['x1', 'x2', 'x3'])
plot_front.plot(front, label='SMPSO-DTLZ2_3', filename='SMPSO-DTLZ2_3', format='png')

In [9]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
spacing_indicator = Spacing(reference_front=reference_front)
Spacing = spacing_indicator.compute(solutions_array)
print(f"Spacing: {Spacing}")

Spacing: 0.0509869703964455


In [10]:
fitness_indicator = FitnessValue(is_minimization=True)
fitness_value = fitness_indicator.compute(front)
print(f"Fitness Value: {fitness_value}")

Fitness Value: 0.5093689797116748


In [11]:
objectives = [solution.objectives for solution in front]
# hypervolume_indicator = HyperVolume(reference_point=[1.0, 1.0])
hypervolume_indicator = HyperVolume(reference_point=[1.0]*3)
hypervolume =  hypervolume_indicator.compute(objectives)
print(f"Hypervolume: {hypervolume}")

Hypervolume: 0.34061777614984406


In [12]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
generational_distance_indicator = GenerationalDistance(reference_front=reference_front)
generational_distance = generational_distance_indicator.compute(solutions_array)
print(f"Generational Distance: {generational_distance}")

<class 'numpy.ndarray'>
Generational Distance: 0.03572084387319267


In [13]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
inverted_generational_distance_indicator = InvertedGenerationalDistance(reference_front=reference_front)
inverted_generational_distance = inverted_generational_distance_indicator.compute(solutions_array)
print(f"Inverted Generational Distance: {inverted_generational_distance}")

Inverted Generational Distance: 0.07404308248559806


In [14]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
epsilon_indicator = EpsilonIndicator(reference_front=reference_front)
Additive_Epsilon = epsilon_indicator.compute(solutions_array)
print(f"Additive_Epsilon: {Additive_Epsilon}")

this is front [[6.38944115e-17 0.00000000e+00 1.04347493e+00]
 [3.89645970e-33 6.36340160e-17 1.03922235e+00]
 [3.21582659e-01 4.42599045e-02 9.65948697e-01]
 [1.09608388e-01 9.55385623e-01 3.80586053e-01]
 [6.31806988e-17 1.03181912e+00 0.00000000e+00]
 [7.93550645e-01 4.82860424e-01 3.90884453e-01]
 [5.36340041e-01 5.09374472e-01 6.90932296e-01]
 [9.20843591e-01 2.41256747e-01 3.55583468e-01]
 [9.37954339e-01 3.13126898e-01 1.48989081e-01]
 [4.57819858e-01 8.43008523e-01 3.16947022e-01]
 [3.56081836e-01 1.86994803e-01 9.35976896e-01]
 [9.51204701e-01 3.03648287e-01 6.91209519e-02]
 [1.00377681e+00 0.00000000e+00 0.00000000e+00]
 [1.67661670e-01 2.94926078e-01 9.54086703e-01]
 [9.65764369e-01 2.03072770e-01 1.94078734e-01]
 [5.07068297e-01 1.20814814e-01 8.82793189e-01]
 [2.80202796e-02 1.40871488e-01 1.01629675e+00]
 [4.07966146e-01 3.36260105e-01 9.04051147e-01]
 [9.78232467e-01 2.17316527e-01 4.96626868e-02]
 [8.43231573e-01 4.01147330e-01 3.68011874e-01]
 [8.31237027e-01 6.1477049