In [1]:
from jmetal.algorithm.multiobjective.gde3 import GDE3
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.algorithm.multiobjective.smpso import *
from jmetal.core.quality_indicator import *
from jmetal.lab.experiment import Experiment, Job, generate_summary_from_experiment
from jmetal.operator import PolynomialMutation, SBXCrossover
from jmetal.util.archive import CrowdingDistanceArchive
from jmetal.util.termination_criterion import StoppingByEvaluations
from jmetal.lab.experiment import generate_boxplot, generate_latex_tables, compute_mean_indicator, compute_wilcoxon
from jmetal.lab.statistical_test.bayesian import *
from jmetal.lab.statistical_test.functions import *
from jmetal.lab.visualization import CDplot, plot_posterior
from jmetal.algorithm.multiobjective import NSGAII
from jmetal.operator import SBXCrossover, PolynomialMutation
from jmetal.problem import DTLZ2
from jmetal.util.termination_criterion import StoppingByEvaluations

In [2]:
problem = DTLZ2(number_of_objectives=3)

algorithm = Chaotic_EMPSO(
    problem=problem,
    swarm_size=100,
    mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables,
                                distribution_index=20),
    leaders=CrowdingDistanceArchive(100),
    termination_criterion=StoppingByEvaluations(max_evaluations=25000)
)

algorithm.run()

In [3]:
from jmetal.util.solution import get_non_dominated_solutions, print_function_values_to_file, print_variables_to_file

front = get_non_dominated_solutions(algorithm.get_result())

# save to files
print_function_values_to_file(front, 'FUN.CHAOTIC_EMPSO.DLTZ2_3')
print_variables_to_file(front, 'VAR.CHAOTIC_EMPSO.DLTZ2_3')

2023-09-27 13:01:50,576 [MainThread  ] [INFO ]  Output file (function values): FUN.CHAOTIC_EMPSO.DLTZ2_3
2023-09-27 13:01:50,578 [MainThread  ] [INFO ]  Output file (variables): VAR.CHAOTIC_EMPSO.DLTZ2_3


In [4]:
from jmetal.lab.visualization import Plot
# plot_front = Plot(title='Pareto front approximation', axis_labels=['x', 'y'])
plot_front = Plot(title='Pareto front approximation', axis_labels=['x1', 'x2', 'x3'])
plot_front.plot(front, label='CHAOTIC_EMPSO-DTLZ2_3', filename='CHAOTIC_EMPSO-DTLZ2_3', format='png')

In [5]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
spacing_indicator = Spacing(reference_front=reference_front)
Spacing = spacing_indicator.compute(solutions_array)
print(f"Spacing: {Spacing}")

Spacing: 0.11576615401612944


In [6]:
fitness_indicator = FitnessValue(is_minimization=True)
fitness_value = fitness_indicator.compute(front)
print(f"Fitness Value: {fitness_value}")

Fitness Value: 0.622098247627477


In [7]:
objectives = [solution.objectives for solution in front]
# hypervolume_indicator = HyperVolume(reference_point=[1.0, 1.0])
hypervolume_indicator = HyperVolume(reference_point=[1.0]*3)
hypervolume =  hypervolume_indicator.compute(objectives)
print(f"Hypervolume: {hypervolume}")

Hypervolume: 0.11168553357277779


In [8]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
generational_distance_indicator = GenerationalDistance(reference_front=reference_front)
generational_distance = generational_distance_indicator.compute(solutions_array)
print(f"Generational Distance: {generational_distance}")

<class 'numpy.ndarray'>
Generational Distance: 0.3473869710748223


In [9]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
inverted_generational_distance_indicator = InvertedGenerationalDistance(reference_front=reference_front)
inverted_generational_distance = inverted_generational_distance_indicator.compute(solutions_array)
print(f"Inverted Generational Distance: {inverted_generational_distance}")

Inverted Generational Distance: 0.251308935307899


In [10]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ2.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
epsilon_indicator = EpsilonIndicator(reference_front=reference_front)
Additive_Epsilon = epsilon_indicator.compute(solutions_array)
print(f"Additive_Epsilon: {Additive_Epsilon}")

this is front [[1.16941233e+00 1.25964809e+00 2.92150721e-02]
 [6.38645913e-01 5.17185216e-01 9.04571320e-01]
 [1.18457497e-01 8.29772402e-01 1.08894387e+00]
 [1.46262657e-16 2.38865047e+00 2.23044292e-01]
 [5.63777542e-01 1.35871898e+00 4.76041313e-01]
 [5.76300887e-01 8.42004429e-01 7.54128289e-01]
 [1.63326541e-01 2.25521174e-01 1.25376248e+00]
 [2.21783084e-01 1.61910217e-01 1.10966549e+00]
 [1.87732440e-01 1.90217085e-01 1.14035914e+00]
 [9.29160352e-01 1.26727959e+00 0.00000000e+00]
 [2.57667130e-01 7.00873050e-01 1.06413127e+00]
 [1.00123870e+00 7.29820028e-01 2.45308011e-01]
 [9.03992745e-01 6.54289085e-01 4.56054232e-01]
 [9.10593515e-01 6.35277642e-01 3.96241150e-01]
 [6.88617963e-01 8.06128054e-01 5.78481041e-01]
 [4.59216810e-03 1.36961816e-01 1.48646718e+00]
 [6.76913141e-01 7.58669215e-01 5.84117486e-01]
 [1.05915030e+00 5.58231051e-01 3.72677719e-01]
 [1.05914704e+00 5.58231067e-01 3.72681504e-01]
 [1.57204627e-16 2.56734640e+00 0.00000000e+00]
 [1.09757671e+00 5.7848742