In [1]:
from jmetal.algorithm.multiobjective.gde3 import GDE3
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.algorithm.multiobjective.smpso import SMPSO
from jmetal.core.quality_indicator import *
from jmetal.lab.experiment import Experiment, Job, generate_summary_from_experiment
from jmetal.operator import PolynomialMutation, SBXCrossover
from jmetal.util.archive import CrowdingDistanceArchive
from jmetal.util.termination_criterion import StoppingByEvaluations
from jmetal.lab.experiment import generate_boxplot, generate_latex_tables, compute_mean_indicator, compute_wilcoxon
from jmetal.lab.statistical_test.bayesian import *
from jmetal.lab.statistical_test.functions import *
from jmetal.lab.visualization import CDplot, plot_posterior
from jmetal.algorithm.multiobjective import NSGAII
from jmetal.operator import SBXCrossover, PolynomialMutation
from jmetal.problem import DTLZ1
from jmetal.util.termination_criterion import StoppingByEvaluations

In [2]:
problem = DTLZ1(number_of_objectives=3)

algorithm = SMPSO(
    problem=problem,
    swarm_size=100,
    mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables,
                                distribution_index=20),
    leaders=CrowdingDistanceArchive(100),
    termination_criterion=StoppingByEvaluations(max_evaluations=25000)
)

algorithm.run()

In [3]:
from jmetal.util.solution import get_non_dominated_solutions, print_function_values_to_file, print_variables_to_file

front = get_non_dominated_solutions(algorithm.get_result())

# save to files
print_function_values_to_file(front, 'FUN.SMPSO.DTLZ1')
print_variables_to_file(front, 'VAR.SMPSO.DTLZ1')

2023-09-27 13:11:21,135 [MainThread  ] [INFO ]  Output file (function values): FUN.SMPSO.DTLZ1
2023-09-27 13:11:21,137 [MainThread  ] [INFO ]  Output file (variables): VAR.SMPSO.DTLZ1


In [4]:
from jmetal.lab.visualization import Plot
# plot_front = Plot(title='Pareto front approximation', axis_labels=['x', 'y'])
plot_front = Plot(title='Pareto front approximation', axis_labels=['x1', 'x2', 'x3'])
plot_front.plot(front, label='SMPSO-DTLZ1', filename='SMPSO-DTLZ1', format='png')

In [5]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
spacing_indicator = Spacing(reference_front=reference_front)
Spacing = spacing_indicator.compute(solutions_array)
print(f"Spacing: {Spacing}")

Spacing: 0.025911457481126016


In [6]:
fitness_indicator = FitnessValue(is_minimization=True)
fitness_value = fitness_indicator.compute(front)
print(f"Fitness Value: {fitness_value}")

Fitness Value: 0.17710798084830381


In [7]:
objectives = [solution.objectives for solution in front]
# hypervolume_indicator = HyperVolume(reference_point=[1.0, 1.0])
hypervolume_indicator = HyperVolume(reference_point=[1.0]*3)
hypervolume =  hypervolume_indicator.compute(objectives)
print(f"Hypervolume: {hypervolume}")

Hypervolume: 0.9672093513737481


In [8]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
generational_distance_indicator = GenerationalDistance(reference_front=reference_front)
generational_distance = generational_distance_indicator.compute(solutions_array)
print(f"Generational Distance: {generational_distance}")

<class 'numpy.ndarray'>
Generational Distance: 0.019923481250178784


In [9]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
inverted_generational_distance_indicator = InvertedGenerationalDistance(reference_front=reference_front)
inverted_generational_distance = inverted_generational_distance_indicator.compute(solutions_array)
print(f"Inverted Generational Distance: {inverted_generational_distance}")

Inverted Generational Distance: 0.028166336312971014


In [10]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
epsilon_indicator = EpsilonIndicator(reference_front=reference_front)
Additive_Epsilon = epsilon_indicator.compute(solutions_array)
print(f"Additive_Epsilon: {Additive_Epsilon}")

this is front [[0.00000000e+00 2.53091422e-01 2.46908578e-01]
 [5.17837090e-01 0.00000000e+00 0.00000000e+00]
 [1.91720142e-02 5.54505008e-02 4.31054490e-01]
 [8.78172432e-02 3.66966432e-01 7.43242068e-02]
 [3.10818771e-01 1.77515491e-01 3.97277806e-02]
 [3.70630860e-01 8.63733466e-02 8.24809547e-02]
 [4.97330731e-02 3.19696620e-01 1.54476192e-01]
 [2.11223148e-01 2.63554106e-01 4.30370466e-02]
 [2.30470801e-01 2.24773678e-01 8.74393128e-02]
 [8.83527088e-03 2.75636688e-01 2.37083955e-01]
 [1.04293791e-01 4.14688578e-01 2.72214567e-02]
 [2.17416644e-01 1.20620249e-01 1.87850614e-01]
 [2.37061898e-01 1.71353952e-01 1.31443634e-01]
 [0.00000000e+00 5.08449284e-01 0.00000000e+00]
 [1.21485057e-01 3.40255693e-01 5.11572973e-02]
 [6.67585695e-02 3.95868006e-01 5.51132089e-02]
 [8.39631874e-02 3.30879497e-01 9.25687867e-02]
 [2.67777154e-01 7.22934978e-02 1.65565065e-01]
 [1.43944238e-01 3.79744650e-01 2.09772318e-02]
 [7.64823216e-03 4.24059000e-01 9.44931759e-02]
 [4.53286362e-02 3.1095584