In [1]:
from jmetal.algorithm.multiobjective.gde3 import GDE3
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.algorithm.multiobjective.smpso import SMPSO
from jmetal.core.quality_indicator import *
from jmetal.lab.experiment import Experiment, Job, generate_summary_from_experiment
from jmetal.operator import PolynomialMutation, SBXCrossover
from jmetal.util.archive import CrowdingDistanceArchive
from jmetal.util.termination_criterion import StoppingByEvaluations
from jmetal.lab.experiment import generate_boxplot, generate_latex_tables, compute_mean_indicator, compute_wilcoxon
from jmetal.lab.statistical_test.bayesian import *
from jmetal.lab.statistical_test.functions import *
from jmetal.lab.visualization import CDplot, plot_posterior
from jmetal.algorithm.multiobjective import NSGAII
from jmetal.operator import SBXCrossover, PolynomialMutation
from jmetal.problem import DTLZ1
from jmetal.util.termination_criterion import StoppingByEvaluations

In [2]:
problem = DTLZ1(number_of_objectives=3)

algorithm = SMPSO(
    problem=problem,
    swarm_size=100,
    mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables,
                                distribution_index=20),
    leaders=CrowdingDistanceArchive(100),
    termination_criterion=StoppingByEvaluations(max_evaluations=25000)
)

algorithm.run()

In [3]:
from jmetal.util.solution import get_non_dominated_solutions, print_function_values_to_file, print_variables_to_file

front = get_non_dominated_solutions(algorithm.get_result())

# save to files
print_function_values_to_file(front, 'FUN.SMPSO.DTLZ1_3')
print_variables_to_file(front, 'VAR.SMPSO.DTLZ1_3')

2023-09-27 14:09:27,065 [MainThread  ] [INFO ]  Output file (function values): FUN.SMPSO.DTLZ1_3
2023-09-27 14:09:27,068 [MainThread  ] [INFO ]  Output file (variables): VAR.SMPSO.DTLZ1_3


In [4]:
from jmetal.lab.visualization import Plot
# plot_front = Plot(title='Pareto front approximation', axis_labels=['x', 'y'])
plot_front = Plot(title='Pareto front approximation', axis_labels=['x1', 'x2', 'x3'])
plot_front.plot(front, label='SMPSO-DTLZ1_3', filename='SMPSO-DTLZ1_3', format='png')

In [5]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
spacing_indicator = Spacing(reference_front=reference_front)
Spacing = spacing_indicator.compute(solutions_array)
print(f"Spacing: {Spacing}")

Spacing: 0.020825217538176028


In [6]:
fitness_indicator = FitnessValue(is_minimization=True)
fitness_value = fitness_indicator.compute(front)
print(f"Fitness Value: {fitness_value}")

Fitness Value: 0.18108611015057022


In [7]:
objectives = [solution.objectives for solution in front]
# hypervolume_indicator = HyperVolume(reference_point=[1.0, 1.0])
hypervolume_indicator = HyperVolume(reference_point=[1.0]*3)
hypervolume =  hypervolume_indicator.compute(objectives)
print(f"Hypervolume: {hypervolume}")

Hypervolume: 0.9648473726143287


In [8]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
generational_distance_indicator = GenerationalDistance(reference_front=reference_front)
generational_distance = generational_distance_indicator.compute(solutions_array)
print(f"Generational Distance: {generational_distance}")

<class 'numpy.ndarray'>
Generational Distance: 0.028289842656914796


In [9]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
inverted_generational_distance_indicator = InvertedGenerationalDistance(reference_front=reference_front)
inverted_generational_distance = inverted_generational_distance_indicator.compute(solutions_array)
print(f"Inverted Generational Distance: {inverted_generational_distance}")

Inverted Generational Distance: 0.03164724533124545


In [10]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
epsilon_indicator = EpsilonIndicator(reference_front=reference_front)
Additive_Epsilon = epsilon_indicator.compute(solutions_array)
print(f"Additive_Epsilon: {Additive_Epsilon}")

this is front [[0.         0.         0.50153157]
 [0.3092607  0.00148538 0.31074608]
 [0.00563753 0.01007992 0.48875011]
 [0.0177227  0.03199456 0.45108806]
 [0.         0.14362585 0.46247574]
 [0.43980662 0.04514738 0.06657062]
 [0.14395228 0.33384434 0.0617157 ]
 [0.39075099 0.13805833 0.02136274]
 [0.11551734 0.06504059 0.33586309]
 [0.46762486 0.06553308 0.00413728]
 [0.4010679  0.02856735 0.11585241]
 [0.05637873 0.05637873 0.43768943]
 [0.27964528 0.12307432 0.14390439]
 [0.04911682 0.1777439  0.30384819]
 [0.01255321 0.09935298 0.40926815]
 [0.56727436 0.         0.        ]
 [0.19896578 0.23958535 0.10496624]
 [0.06260739 0.42626681 0.04374987]
 [0.06433802 0.16122466 0.34401825]
 [0.00641026 0.49023125 0.02851939]
 [0.22651162 0.27684753 0.02151839]
 [0.36002899 0.10579213 0.04750898]
 [0.2081688  0.11954728 0.24783699]
 [0.         0.51745559 0.03231668]
 [0.25465947 0.1081466  0.17103565]
 [0.13866704 0.2660411  0.12427662]
 [0.54459119 0.         0.07202814]
 [0.12708143 0