In [1]:
from jmetal.algorithm.multiobjective.gde3 import GDE3
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.algorithm.multiobjective.smpso import *
from jmetal.core.quality_indicator import *
from jmetal.lab.experiment import Experiment, Job, generate_summary_from_experiment
from jmetal.operator import PolynomialMutation, SBXCrossover
from jmetal.util.archive import CrowdingDistanceArchive
from jmetal.util.termination_criterion import StoppingByEvaluations
from jmetal.lab.experiment import generate_boxplot, generate_latex_tables, compute_mean_indicator, compute_wilcoxon
from jmetal.lab.statistical_test.bayesian import *
from jmetal.lab.statistical_test.functions import *
from jmetal.lab.visualization import CDplot, plot_posterior
from jmetal.algorithm.multiobjective import NSGAII
from jmetal.operator import SBXCrossover, PolynomialMutation
from jmetal.problem import DTLZ1
from jmetal.util.termination_criterion import StoppingByEvaluations

In [2]:
problem = DTLZ1(number_of_objectives=3)

algorithm = Chaotic_EMPSO(
    problem=problem,
    swarm_size=100,
    mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables,
                                distribution_index=20),
    leaders=CrowdingDistanceArchive(100),
    termination_criterion=StoppingByEvaluations(max_evaluations=25000)
)

algorithm.run()

In [3]:
from jmetal.util.solution import get_non_dominated_solutions, print_function_values_to_file, print_variables_to_file

front = get_non_dominated_solutions(algorithm.get_result())

# save to files
print_function_values_to_file(front, 'FUN.CHAOTIC_EMPSO.DLTZ1_3')
print_variables_to_file(front, 'VAR.CHAOTIC_EMPSO.DLTZ1_3')

2023-09-27 11:10:21,628 [MainThread  ] [INFO ]  Output file (function values): FUN.CHAOTIC_EMPSO.DLTZ1_3
2023-09-27 11:10:21,629 [MainThread  ] [INFO ]  Output file (variables): VAR.CHAOTIC_EMPSO.DLTZ1_3


In [4]:
from jmetal.lab.visualization import Plot
# plot_front = Plot(title='Pareto front approximation', axis_labels=['x', 'y'])
plot_front = Plot(title='Pareto front approximation', axis_labels=['x1', 'x2', 'x3'])
plot_front.plot(front, label='CHAOTIC_EMPSO-DTLZ1_3', filename='CHAOTIC_EMPSO-DTLZ1_3', format='png')

In [6]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
spacing_indicator = Spacing(reference_front=reference_front)
Spacing = spacing_indicator.compute(solutions_array)
print(f"Spacing: {Spacing}")

Spacing: 7.823262827084495


In [7]:
fitness_indicator = FitnessValue(is_minimization=True)
fitness_value = fitness_indicator.compute(front)
print(f"Fitness Value: {fitness_value}")

Fitness Value: 16.900306693658315


In [14]:
objectives = [solution.objectives for solution in front]
# hypervolume_indicator = HyperVolume(reference_point=[1.0, 1.0])
hypervolume_indicator = HyperVolume(reference_point=[1.0]*3)
hypervolume =  hypervolume_indicator.compute(objectives)
print(f"Hypervolume: {hypervolume}")

Hypervolume: 0.0


In [9]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
generational_distance_indicator = GenerationalDistance(reference_front=reference_front)
generational_distance = generational_distance_indicator.compute(solutions_array)
print(f"Generational Distance: {generational_distance}")

<class 'numpy.ndarray'>
Generational Distance: 41.29418412581759


In [10]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
inverted_generational_distance_indicator = InvertedGenerationalDistance(reference_front=reference_front)
inverted_generational_distance = inverted_generational_distance_indicator.compute(solutions_array)
print(f"Inverted Generational Distance: {inverted_generational_distance}")

Inverted Generational Distance: 16.14303768974126


In [11]:
reference_front_file_path = '/home/anuj/Documents/jMetalPy/resources/reference_front/DTLZ1.3D.pf'
reference_front = np.loadtxt(reference_front_file_path)
solutions_array = np.array([solution.objectives for solution in front])
epsilon_indicator = EpsilonIndicator(reference_front=reference_front)
Additive_Epsilon = epsilon_indicator.compute(solutions_array)
print(f"Additive_Epsilon: {Additive_Epsilon}")

this is front [[1.30314883e+00 5.50349470e+00 1.54262371e+01]
 [0.00000000e+00 2.39763507e+01 4.74935074e+01]
 [0.00000000e+00 3.11113460e+01 3.51907632e+01]
 [9.02381573e+00 4.08537295e-02 2.40668891e+01]
 [5.99701774e+01 8.25298915e+00 1.45946496e+00]
 [6.12129859e+01 8.42537019e+00 7.52399721e-02]
 [6.12235129e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.14220746e+01]
 [0.00000000e+00 5.25214859e+01 0.00000000e+00]
 [9.72835081e+00 1.45925263e+01 8.20724677e+00]
 [1.57886092e+01 0.00000000e+00 4.91682143e+01]
 [2.16418068e+00 2.51354520e+00 4.28578026e+01]
 [8.38784110e+00 4.69310803e-01 2.34852044e+01]
 [6.20840574e-01 1.37222050e+01 4.51965942e+01]
 [5.16588168e+00 4.38349091e+01 3.40542658e+00]
 [5.76596542e+00 1.44150218e+00 2.88294275e+01]
 [2.89495907e+01 7.07118069e+00 8.79842303e+00]
 [2.87684502e+01 7.11329840e+00 8.87032662e+00]]
Additive_Epsilon: 14.592526311098952
